<<<<<<< HEAD
=======
CREATE TABLE `user`(
    id BINARY(16) NOT NULL PRIMARY KEY, 
    name VARCHAR(32) NOT NULL, 
    email VARCHAR(128) NOT NULL, 
    provider VARCHAR(16) NOT NULL, 
    provider_id VARCHAR(64) NULL, 
    workspace_id INTEGER NULL, 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP NULL, 
    deleted_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE refresh_tokens(
    id BINARY(16) NOT NULL PRIMARY KEY, 
    user_id BINARY(16) NOT NULL, 
    token VARCHAR(255) NOT NULL, 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP, 
    deleted_at TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

>>>>>>> 20884946d6aeb1153f26862c914a8b6d559d5d6c
CREATE TABLE messages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tab_id INT NOT NULL,
    sender_id BINARY(16) NOT NULL,
    content TEXT NOT NULL,
    is_updated BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE workspace_members (
    id BINARY(16) PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    workspace_id INT NOT NULL,
    nickname VARCHAR(32) NOT NULL DEFAULT '익명의 오징어',
    email VARCHAR(128) NOT NULL,
    image VARCHAR(255) NOT NULL,
    role_id INT NOT NULL,
    group_id INT DEFAULT NULL,
    github VARCHAR(255) DEFAULT NULL,
    blog VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
