CREATE TABLE messages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tab_id INT NOT NULL,
    sender_id BINARY(16) NOT NULL,
    content TEXT NOT NULL,
    is_updated BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE workspace_members (
    id BINARY(16) PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    workspace_id INT NOT NULL,
    nickname VARCHAR(32) NOT NULL DEFAULT '익명의 오징어',
    email VARCHAR(128) NOT NULL,
    image VARCHAR(255) NOT NULL,
    role_id INT NOT NULL,
    group_id INT DEFAULT NULL,
    github VARCHAR(255) DEFAULT NULL,
    blog VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
